
return {}

--return {
--"hrsh7th/nvim-cmp",
--dependencies = {
--     "neovim/nvim-lspconfig",
--     "hrsh7th/cmp-nvim-lsp",
--     "hrsh7th/cmp-buffer",
--     "hrsh7th/cmp-path",
--     "hrsh7th/cmp-cmdline",
--      -- For luasnip users.,
--	 {
--		 "L3MON4D3/LuaSnip",
--		 opts = function()
--		 		local ls = require("luasnip")
--
--				vim.keymap.set({"i"}, "<C-K>", function() ls.expand() end, {silent = true})
--				vim.keymap.set({"i", "s"}, "<C-L>", function() ls.jump( 1) end, {silent = true})
--				vim.keymap.set({"i", "s"}, "<C-J>", function() ls.jump(-1) end, {silent = true})
--				
--				vim.keymap.set({"i", "s"}, "<C-E>", function()
--					if ls.choice_active() then
--						ls.change_choice(1)
--					end
--				end, {silent = true})
--			end
--	 },
--     "saadparwaiz1/cmp_luasnip"
--},
--  opts = function()
--    -- Set up nvim-cmp.
--    local cmp = require("cmp")
--    return {
--        snippet = {
--            -- REQUIRED - you must specify a snippet engine
--            expand = function(args)
--                require("luasnip").lsp_expand(args.body) -- For `luasnip` users.
--            end
--        },
--        window = {
--            --completion = cmp.config.window.bordered(),
--            --documentation = cmp.config.window.bordered()
--        },
--        --mapping = cmp.mapping.preset.insert(
--        --    {
--        --        ["<C-b>"] = cmp.mapping.scroll_docs(-4),
--        --        ["<C-f>"] = cmp.mapping.scroll_docs(4),
--        --        ["<C-Space>"] = cmp.mapping.complete(),
--        --        ["<C-e>"] = cmp.mapping.abort(),
--        --        ["<CR>"] = cmp.mapping.confirm({select = true}) -- Accept currently selected item. Set `select` to `false` to only confirm explicitly selected items.
--        --    }
--        --),
--        sources = cmp.config.sources(
--            {
--                {name = "luasnip"}, -- For luasnip users.
--                {name = "nvim_lsp"}
--            },
--            {
--                {name = "buffer"}
--            }
--        )
--    }
--	end,
--}
